table 'Amazon Price Tracker_brand_asins'
	lineageTag: f09ca0c2-588b-4d9b-8343-8745ee079d34

	column Account
		dataType: string
		lineageTag: 075728aa-f389-4fa5-bdcb-598d0d305f44
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: 6d494171-cd8a-44e4-8ce5-98dc73ede1af
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 4ba46ee6-a33e-4252-8c8c-0d3d68579260
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub Category'
		dataType: string
		lineageTag: aa234e26-89ce-4793-91e9-0116acaa66d0
		summarizeBy: none
		sourceColumn: Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Brand ASIN'
		dataType: string
		lineageTag: d84300f2-a328-4dde-b1fe-a61dfd7480ca
		summarizeBy: none
		sourceColumn: Brand ASIN

		annotation SummarizationSetBy = Automatic

	column 'Comp 1 ASIN'
		dataType: string
		lineageTag: 14ecac5a-ae3d-4830-ac17-679676b2e334
		summarizeBy: none
		sourceColumn: Comp 1 ASIN

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: string
		lineageTag: 7c75f60a-d377-4f3b-85f5-f00cbc98668d
		summarizeBy: none
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	column brand_comp
		dataType: string
		lineageTag: 286c5260-a460-416c-8971-0757ae740bcd
		summarizeBy: none
		sourceColumn: brand_comp

		annotation SummarizationSetBy = Automatic

	column 'Comp 2 ASIN'
		dataType: string
		lineageTag: 1f90639e-0c25-486c-a96e-01d3598259d7
		summarizeBy: none
		sourceColumn: Comp 2 ASIN

		annotation SummarizationSetBy = Automatic

	column 'Comp 2 Price'
		dataType: string
		lineageTag: 1ab68095-ef63-4ed3-875d-a2b6db095bba
		summarizeBy: none
		sourceColumn: Comp 2 Price

		annotation SummarizationSetBy = Automatic

	partition 'Amazon Price Tracker_brand_asins' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1kC_MKRIbnrqCfHjvYNUP6URIJDGr_yUmTvB8x0B2wHM/edit?gid=905270041#gid=905270041"),
				    #"Target VS Achieved_Table" = Source{[name="Amazon - Price Tracker",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Target VS Achieved_Table", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Brand Price", "Comp 1 Price", "Comp 1 ASIN"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Added Custom" = Table.AddColumn(#"Removed Duplicates", "Comp 1 ASIN", each [Brand ASIN]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "sort_order", each 1),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "brand_comp", each "Brand")
				in
				    #"Added Custom2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

