table 'Flipkart Price Tracker_brand_fsn'
	lineageTag: 1f564192-ed73-4557-b340-a2a86615e187

	column Account
		dataType: string
		lineageTag: eac9317f-7247-4cb2-8a30-5e5c493123f3
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: e5f669fb-cbc3-4b39-80ce-d2b2e137c2eb
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 5a60aa00-288a-423b-a21f-ccbc2f94e9ce
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub Category'
		dataType: string
		lineageTag: 9104bb54-d4cd-42ad-bb7d-535a1ff6fba5
		summarizeBy: none
		sourceColumn: Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Brand FSN'
		dataType: string
		lineageTag: 0753d221-356f-44e1-bca8-128a35405020
		summarizeBy: none
		sourceColumn: Brand FSN

		annotation SummarizationSetBy = Automatic

	column 'Comp 1 FSN'
		dataType: string
		lineageTag: fca73aa3-4fc1-46ea-ac44-b8d66443a42c
		summarizeBy: none
		sourceColumn: Comp 1 FSN

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: c36a2852-e728-4cb8-8447-9fc388555c63
		summarizeBy: sum
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	column brand_comp
		dataType: string
		lineageTag: 814027dc-a5e0-4b1c-b301-404b6aa662c4
		summarizeBy: none
		sourceColumn: brand_comp

		annotation SummarizationSetBy = Automatic

	partition 'Flipkart Price Tracker_brand_fsn' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1kC_MKRIbnrqCfHjvYNUP6URIJDGr_yUmTvB8x0B2wHM/edit?gid=401136123#gid=401136123"),
				    #"Target VS Achieved_Table" = Source{[name="Flipkart - Price Tracker",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Target VS Achieved_Table", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Brand Price", "Comp 1 Price", "Comp 1 FSN"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Added Custom" = Table.AddColumn(#"Removed Duplicates", "Comp 1 FSN", each [Brand FSN]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "sort_order", each 1),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"sort_order", Int64.Type}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type", "brand_comp", each "Brand")
				in
				    #"Added Custom2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

