table 'Flipkart Price Tracker'
	lineageTag: 98f32c5c-996f-4fd6-9278-5dee4fd6ee8b

	column Account
		dataType: string
		lineageTag: c8868269-9818-4aa0-8599-5abd38de296b
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: 17f90db1-5a39-461e-9e4b-a7c09eb265f1
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b25b6c34-f865-4051-b995-d690bcdb3d49
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub Category'
		dataType: string
		lineageTag: c775f6dd-77ae-44dd-899f-58afa1796ff7
		summarizeBy: none
		sourceColumn: Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Brand FSN'
		dataType: string
		lineageTag: 98db741d-002a-4aed-9725-b73772d39124
		summarizeBy: none
		sourceColumn: Brand FSN

		annotation SummarizationSetBy = Automatic

	column 'Comp 1 FSN'
		dataType: string
		lineageTag: bdda2ed8-9675-486e-b972-ff8bffb171fd
		summarizeBy: none
		sourceColumn: Comp 1 FSN

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: string
		lineageTag: 88111cda-a5a9-482c-83b2-e30ea99efb49
		summarizeBy: none
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	partition 'Flipkart Price Tracker' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1kC_MKRIbnrqCfHjvYNUP6URIJDGr_yUmTvB8x0B2wHM/edit?gid=401136123#gid=401136123"),
				    #"Target VS Achieved_Table" = Source{[name="Flipkart - Price Tracker",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Target VS Achieved_Table", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Brand Price", "Comp 1 Price"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "sort_order", each 2)
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

