table flipkart_price_tracker_master
	lineageTag: 3e624db2-2b96-46ee-a346-ac7e309f4210

	column Account
		dataType: string
		lineageTag: 8d1b7ba4-f88a-4918-90a1-630370583f36
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: c4ae5360-4aba-4f62-b112-c022b718f735
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 8934359e-9b77-4184-a630-7292eca7dcc6
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub Category'
		dataType: string
		lineageTag: d055d21b-0342-4729-957e-da03067f689d
		summarizeBy: none
		sourceColumn: Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Brand FSN'
		dataType: string
		lineageTag: 9f999878-68a9-47db-89d3-e4a1422bd273
		summarizeBy: none
		sourceColumn: Brand FSN

		annotation SummarizationSetBy = Automatic

	column 'Comp 1 FSN'
		dataType: string
		lineageTag: 0e064de9-4860-494d-ba42-db56ea0e9bdf
		summarizeBy: none
		sourceColumn: Comp 1 FSN

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 047e7896-3567-4161-a9e0-c6b2c629f648
		summarizeBy: none
		sourceColumn: sort_order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = User

	column brand_comp
		dataType: string
		lineageTag: 29847ca9-f08b-46b9-9b7b-6d15bf6230e5
		summarizeBy: none
		sourceColumn: brand_comp

		annotation SummarizationSetBy = Automatic

	partition flipkart_price_tracker_master = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Flipkart Price Tracker_brand_fsn", #"Flipkart Price Tracker"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Account] = "OneTouch")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"sort_order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

