table 'public amazon_sov'
	lineageTag: 87221efa-84ed-43ef-a2d1-0e9021c06b5d

	measure 'Total Sponsored Slots' =
			
			CALCULATE (
			    COUNTROWS ( 'public amazon_sov' ),
			    'public amazon_sov'[is_sponsored] = "Sponsored"
			)
		formatString: 0
		lineageTag: 7278f0e7-3d0a-430a-a324-17e24b5e59e3

	measure 'Total Organic Slots' =
			
			CALCULATE (
			    COUNTROWS ( 'public amazon_sov' ),
			    'public amazon_sov'[is_sponsored] = "Organic"
			)
		formatString: 0
		lineageTag: fc4b61da-e2cf-4c74-afaf-4b0baeaa351f

	measure 'Total Slots' = COUNTROWS ( 'public amazon_sov' )
		formatString: 0
		lineageTag: 6b5ca8ff-c0a3-43d5-b121-39b2e96f0fe1

	measure 'SoV % Overall' =
			
			DIVIDE (
			    COUNTROWS ( 'public amazon_sov' ),
			    CALCULATE (
			        COUNTROWS ( 'public amazon_sov'),
			        ALL ( 'public amazon_sov'[brand_vs_comp] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 22d1d114-b5c7-48cc-9537-71b811106798

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9f4091d4-d97b-44bd-813c-f170cd674b56
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: d857be2d-51a9-4cfe-8102-b07cc19ad1a2
			defaultHierarchy: LocalDateTable_4038819a-87eb-4c82-acd2-4488c1ac1e5f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column keyword
		dataType: string
		lineageTag: 9ca6b3c7-7e4b-4a9d-ae2e-5b9184f0f18b
		summarizeBy: none
		sourceColumn: keyword

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 63806e0f-4f3f-4a83-b227-9d3ff867332f
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column is_sponsored
		dataType: string
		lineageTag: 0768c478-c5bd-4803-a608-3722b9da6e4b
		summarizeBy: none
		sourceColumn: is_sponsored

		annotation SummarizationSetBy = Automatic

	column price
		dataType: string
		lineageTag: 063e7f16-d9f7-4df3-83b6-f040436c21c7
		summarizeBy: none
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column slot
		dataType: int64
		formatString: 0
		lineageTag: ba5194df-218b-44c7-bca6-23db96b6352e
		summarizeBy: sum
		sourceColumn: slot

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column page_result
		dataType: string
		lineageTag: 3ea7711e-cdf5-4f75-9eff-345c97bd4404
		summarizeBy: none
		sourceColumn: page_result

		annotation SummarizationSetBy = Automatic

	column asin
		dataType: string
		lineageTag: 03329a16-8725-4fce-b125-5199663d98af
		summarizeBy: none
		sourceColumn: asin

		annotation SummarizationSetBy = Automatic

	column hour
		dataType: string
		lineageTag: d83f73a9-afbf-4717-9131-980706322f20
		summarizeBy: none
		sourceColumn: hour

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: a969dab5-617b-4941-90f3-0f785c9aa5c1
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: 627a9e07-38ba-4bc2-89ff-46961d2a606f
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column Brand_Status = ```
			
			SWITCH(
			    TRUE(),
			    SEARCH("jockey", LOWER('public amazon_sov'[title]), 1, 0) > 0, "Brand",
			    "Other"
			)
			
			
			```
		lineageTag: f43d14bc-4473-4696-8a79-eef32cb20600
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Combined_Account_Keyword = ```
			FORMAT('public amazon_sov'[account], "") & " - " & FORMAT('public amazon_sov'[keyword], "")
			
			```
		lineageTag: b1e5087d-24d8-4a9f-8ccf-8c5c0f1d854a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 106acbf6-1948-44e6-80ac-ebe296cb334a
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column sub_category
		dataType: string
		lineageTag: 26ca35b8-fa60-4d64-9b0d-e77911419ae6
		summarizeBy: none
		sourceColumn: sub_category

		annotation SummarizationSetBy = Automatic

	column BCG
		dataType: string
		lineageTag: e41c5854-a60e-4146-b69f-069c94f3f567
		summarizeBy: none
		sourceColumn: BCG

		annotation SummarizationSetBy = Automatic

	column sub_category_1
		dataType: string
		lineageTag: bb4b2dc9-98a7-4999-b15b-9b44185037e4
		summarizeBy: none
		sourceColumn: sub_category_1

		annotation SummarizationSetBy = Automatic

	column sub_category_2
		dataType: string
		lineageTag: b8d792ce-049d-4fd7-879a-db04f608857a
		summarizeBy: none
		sourceColumn: sub_category_2

		annotation SummarizationSetBy = Automatic

	column sub_category_3
		dataType: string
		lineageTag: fbf6117d-3fa4-4491-a5f4-f379367b7921
		summarizeBy: none
		sourceColumn: sub_category_3

		annotation SummarizationSetBy = Automatic

	column 'Good Rank' =
			
			IF (
			    'public amazon_sov'[is_sponsored] = "Sponsored" && 'public amazon_sov'[slot] < 5,
			    "Yes",
			    "No"
			)
		lineageTag: b85315f5-a47f-4911-a7cb-31e729f31ef2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column brand_vs_comp = ```
			
			IF (
			 LOWER('public amazon_sov'[brand]) = "jockey",
			    "Brand",
			    "Comp"
			)
			
			```
		lineageTag: 6842fd2b-8538-4e01-81a8-5a36daba2bf6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'public amazon_sov' = m
		mode: import
		source =
				let
				    Source = Table.SelectRows(
				    PostgreSQL.Database("nucleus.ckojnefw0d56.us-west-1.rds.amazonaws.com", "GIF_2025"){[Schema="public", Item="amazon_sov"]}[Data],
				    each [account] = "Jockey"
				)
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

