table Sale_2024-Fk
	lineageTag: c1f98490-6ab9-41ca-b208-f3b861a8efd3

	column BBD
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5a2dab28-714d-4b1f-9ccf-28d5f5ba24a6
		summarizeBy: none
		sourceColumn: BBD

		variation Variation
			isDefault
			relationship: ca1a9be8-6b10-4b91-a955-f45ca9af8b5b
			defaultHierarchy: LocalDateTable_f44cdcf4-37f9-4c54-bfd7-5625cf54bd8a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Impressions
		dataType: int64
		formatString: 0
		lineageTag: baac993c-3783-4913-ac85-976473c42055
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

	column Clicks
		dataType: int64
		formatString: 0
		lineageTag: b5623456-4360-414e-897b-fd7b6ae8c78a
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

	column Spends
		dataType: int64
		formatString: 0
		lineageTag: 16f91877-60c8-4127-852e-10a98812680e
		summarizeBy: sum
		sourceColumn: Spends

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: int64
		formatString: 0
		lineageTag: 6d8b2dad-e66f-4d49-b4cc-3cd8a916cba3
		summarizeBy: sum
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: int64
		formatString: 0
		lineageTag: 90436bbd-7037-4635-84fc-595d8a0b90ec
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column CTR
		dataType: double
		lineageTag: 0c444707-501a-44eb-93c5-d65187b20ba4
		summarizeBy: sum
		sourceColumn: CTR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CPC
		dataType: double
		lineageTag: 81206c3a-03a4-4386-b242-1a4e99b69ed6
		summarizeBy: sum
		sourceColumn: CPC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CVR
		dataType: double
		lineageTag: 5218500c-654e-4a39-9bcc-b35976df19ac
		summarizeBy: sum
		sourceColumn: CVR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AOV
		dataType: double
		lineageTag: 12009bfc-55f8-4ec9-8514-faec3a15fd7f
		summarizeBy: sum
		sourceColumn: AOV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ROI
		dataType: double
		lineageTag: ee667495-6851-41f5-909d-58504f171602
		summarizeBy: sum
		sourceColumn: ROI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sale_2024-Fk = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Z8q637lN1Fymvf04HEbakg_HdDybg_RrO4R846rZSzc/edit?gid=1273214790#gid=1273214790"),
				    Sale_2024_Table = Source{[name="Flipkart-Sale_2024",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sale_2024_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"BBD", type date}, {"Impressions", Int64.Type}, {"Clicks", Int64.Type}, {"Spends", Int64.Type}, {"Orders", Int64.Type}, {"Sales", Int64.Type}, {"CTR", type number}, {"CPC", type number}, {"CVR", type number}, {"AOV", type number}, {"ROI", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

