table 'Target VS Achieved-Fk'
	lineageTag: afed3046-2f1e-4502-8bf6-8fb81068ecda

	measure CTR_tf = DIVIDE((SUM('Target VS Achieved-Fk'[Clicks])),(SUM('Target VS Achieved-Fk'[Impressions])),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3b1ce186-677c-44c9-830e-5c268321fd71

	measure CVR_Tf = DIVIDE((SUM('Target VS Achieved-Fk'[Orders])),(SUM('Target VS Achieved-Fk'[Clicks])),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 389ecab8-7c2e-411a-9d1a-c1cd79f112f5

	measure AOV_tf = DIVIDE((SUM('Target VS Achieved-Fk'[Sales])),(SUM('Target VS Achieved-Fk'[Orders])),0)
		lineageTag: 1427cdb8-0439-4028-b8a1-afdc0fccbba3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ACOS_Tf = DIVIDE((SUM('Target VS Achieved-Fk'[Spends])),(SUM('Target VS Achieved-Fk'[Sales])),0)
		lineageTag: 7abd067e-e1cd-4197-a97c-6bb30080c693

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ROAS_Tf = DIVIDE((SUM('Target VS Achieved-Fk'[Sales])),(SUM('Target VS Achieved-Fk'[Spends])),0)
		lineageTag: ea50ca0b-2e59-4289-83a7-19d0b5505e65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FK-CPC = DIVIDE(SUM('Target VS Achieved-Fk'[Spends]), HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_clicks], 0)
		lineageTag: 0df4fef9-e536-4d5a-ba61-a11e4feeb0a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %Spends-FK = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_Spends], SUM('Target VS Achieved-Fk'[Spends]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2ecbc35c-2666-40b0-ae08-304e8825e9e4

	measure %Clicks-FK = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_clicks], sum('Target VS Achieved-Fk'[Clicks]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 645f8b51-2c00-4560-b2c2-016f96f51bbc

	measure %Orders-FK = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_orders], sum('Target VS Achieved-Fk'[Orders]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 32632488-4595-426f-b04d-1d3327377826

	measure %Sales-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_sales], sum('Target VS Achieved-Fk'[Sales]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b6ccf600-1e6e-48ff-b383-a5565505f823

	measure %CVR-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_cvr], 'Target VS Achieved-Fk'[CVR_Tf])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eaf409e6-1888-4680-b493-1621e0067a98

	measure %CPC-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_cpc], 'Target VS Achieved-Fk'[FK-CPC])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9e6082a5-bd70-445d-b07c-10a3dd37894b

	measure %AOV-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_AOV], 'Target VS Achieved-Fk'[AOV_tf])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2ea72388-4330-4aca-8187-c5bb004bb14a

	measure %ROI-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_roas], 'Target VS Achieved-Fk'[ROAS_Tf])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7d692fab-60eb-45c7-9f8e-4a39b4ee5703

	measure %Impressions-Fk = DIVIDE(sum(HIVEMINDS_FLIPKART_HOURLY_VIEW[VIEWS]), sum('Target VS Achieved-Fk'[Impressions]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 34603fac-0af9-4a70-b2c7-76f12a80a284

	measure %CTR-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_ctr], 'Target VS Achieved-Fk'[CTR_tf], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a131f5c8-5e03-4f33-96a6-64e7962bac77

	column Impressions
		dataType: double
		lineageTag: 89c2b809-2a6a-4943-ac0c-969c43d10093
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Clicks
		dataType: double
		lineageTag: 5e15e05e-0b25-497c-8ee3-90ac4d8eb057
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Spends
		dataType: int64
		formatString: 0
		lineageTag: ab5045f4-753d-4790-9138-69b46b63bfcc
		summarizeBy: sum
		sourceColumn: Spends

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: int64
		formatString: 0
		lineageTag: 91e4a87b-dbd0-48fb-bb5a-02a28e4779f6
		summarizeBy: sum
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: cb50b1bc-66e3-4ffd-abdb-4e392415ea6f
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CTR
		dataType: double
		lineageTag: aaee7bde-ebdb-4bb7-9183-07ef258522cf
		summarizeBy: sum
		sourceColumn: CTR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CPC
		dataType: double
		lineageTag: 4938a8b7-0a2e-4697-aa68-348767ba7d27
		summarizeBy: sum
		sourceColumn: CPC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CVR
		dataType: double
		lineageTag: 36deffb7-9729-48f0-ad3e-a73bac59bc4f
		summarizeBy: sum
		sourceColumn: CVR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AOV
		dataType: double
		lineageTag: 447343e8-9031-4a19-b9c1-c7c451f71792
		summarizeBy: sum
		sourceColumn: AOV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ROI
		dataType: double
		lineageTag: 5234bbc3-473b-4324-86d2-5e7c0389c9de
		summarizeBy: sum
		sourceColumn: ROI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d10b9a61-e2de-4146-b73f-e389b3058d0e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 318ec229-eaf0-415e-9cb0-e02d18436e33
			defaultHierarchy: LocalDateTable_770c368e-deec-412f-9332-4fe1f12d9c96.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Target VS Achieved-Fk' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Z8q637lN1Fymvf04HEbakg_HdDybg_RrO4R846rZSzc/edit?gid=1273214790#gid=1273214790"),
				    #"Target VS Achieved_Table" = Source{[name="Target VS Achieved - Flipkart",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Target VS Achieved_Table", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Impressions", type number}, {"Clicks", type number}, {"Spends", Int64.Type}, {"Orders", Int64.Type}, {"Sales", type number}, {"CTR", type number}, {"CPC", type number}, {"CVR", type number}, {"AOV", type number}, {"ROI", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Date] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

