table 'Target VS Achieved'
	lineageTag: 7cbf1518-44ec-4330-89a8-5a534ae2f560

	column KPI
		dataType: string
		lineageTag: 3e7047e9-10a7-4117-bfb4-2eafd110bf0b
		summarizeBy: none
		sourceColumn: KPI

		annotation SummarizationSetBy = Automatic

	column 'GIF 2025'
		dataType: double
		lineageTag: 0e91518c-5791-4365-8519-faeee73ee377
		summarizeBy: sum
		sourceColumn: GIF 2025

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Target VS Achieved' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Z8q637lN1Fymvf04HEbakg_HdDybg_RrO4R846rZSzc/edit?gid=1273214790#gid=1273214790"),
				    #"Target VS Achieved_Table" = Source{[name="Target VS Achieved",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Target VS Achieved_Table", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"KPI", type text}, {"GIF 2025", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

