table 'Target VS Achieved-Fk'
	lineageTag: afed3046-2f1e-4502-8bf6-8fb81068ecda

	measure CTR_tf = DIVIDE((SUM('Target VS Achieved-Fk'[Clicks])),(SUM('Target VS Achieved-Fk'[Impressions])),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3b1ce186-677c-44c9-830e-5c268321fd71

	measure CVR_Tf = DIVIDE((SUM('Target VS Achieved-Fk'[Orders])),(SUM('Target VS Achieved-Fk'[Clicks])),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 389ecab8-7c2e-411a-9d1a-c1cd79f112f5

	measure AOV_tf = DIVIDE((SUM('Target VS Achieved-Fk'[Ad Sales])),(SUM('Target VS Achieved-Fk'[Orders])),0)
		lineageTag: 1427cdb8-0439-4028-b8a1-afdc0fccbba3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ACOS_Tf = DIVIDE((SUM('Target VS Achieved-Fk'[Spends])),(SUM('Target VS Achieved-Fk'[Ad Sales])),0)
		lineageTag: 7abd067e-e1cd-4197-a97c-6bb30080c693

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ROAS_Tf = DIVIDE((SUM('Target VS Achieved-Fk'[Ad Sales])),(SUM('Target VS Achieved-Fk'[Spends])),0)
		lineageTag: ea50ca0b-2e59-4289-83a7-19d0b5505e65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FK-CPC = DIVIDE(SUM('Target VS Achieved-Fk'[Spends]), HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_clicks], 0)
		lineageTag: 0df4fef9-e536-4d5a-ba61-a11e4feeb0a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %Spends-FK = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_Spends], SUM('Target VS Achieved-Fk'[Spends]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2ecbc35c-2666-40b0-ae08-304e8825e9e4

	measure %Clicks-FK = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_clicks], sum('Target VS Achieved-Fk'[Clicks]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 645f8b51-2c00-4560-b2c2-016f96f51bbc

	measure %Orders-FK = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_orders], sum('Target VS Achieved-Fk'[Orders]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 32632488-4595-426f-b04d-1d3327377826

	measure %Sales-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[FK_sales], sum('Target VS Achieved-Fk'[Ad Sales]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b6ccf600-1e6e-48ff-b383-a5565505f823

	measure %CVR-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_cvr], 'Target VS Achieved-Fk'[CVR_Tf])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eaf409e6-1888-4680-b493-1621e0067a98

	measure %CPC-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_cpc], 'Target VS Achieved-Fk'[FK-CPC])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9e6082a5-bd70-445d-b07c-10a3dd37894b

	measure %AOV-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_AOV], 'Target VS Achieved-Fk'[AOV_tf])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2ea72388-4330-4aca-8187-c5bb004bb14a

	measure %ROI-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_roas], 'Target VS Achieved-Fk'[ROAS_Tf])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7d692fab-60eb-45c7-9f8e-4a39b4ee5703

	measure %Impressions-Fk = DIVIDE(sum(HIVEMINDS_FLIPKART_HOURLY_VIEW[VIEWS]), sum('Target VS Achieved-Fk'[Impressions]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 34603fac-0af9-4a70-b2c7-76f12a80a284

	measure %CTR-Fk = DIVIDE(HIVEMINDS_FLIPKART_HOURLY_VIEW[fk_ctr], 'Target VS Achieved-Fk'[CTR_tf], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a131f5c8-5e03-4f33-96a6-64e7962bac77

	column Spends
		dataType: int64
		formatString: 0
		lineageTag: ab5045f4-753d-4790-9138-69b46b63bfcc
		summarizeBy: sum
		sourceColumn: Spends

		annotation SummarizationSetBy = Automatic

	column Account
		dataType: string
		lineageTag: 55b1ba87-61e0-4231-93fa-5df940257bce
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: a21944b3-96c9-406b-8f92-77bf194f2423
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column 'Sale Type'
		dataType: string
		lineageTag: 211c2758-9f2e-43ac-a8e0-dc843b9a7779
		summarizeBy: none
		sourceColumn: Sale Type

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: d88f85e6-f1e6-40d7-9db1-6afea580c85d
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Ad Sales'
		dataType: double
		lineageTag: 81374a3d-6ae2-4dfe-ae4b-89ec898a2a05
		summarizeBy: sum
		sourceColumn: Ad Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Overall Sales'
		dataType: int64
		formatString: 0
		lineageTag: f26b4a1f-2f7e-4cdf-9ef6-20991fdf520b
		summarizeBy: sum
		sourceColumn: Overall Sales

		annotation SummarizationSetBy = Automatic

	column 'Paid ROI'
		dataType: double
		lineageTag: d44e238d-4546-4c9a-9236-ea96c3489be7
		summarizeBy: sum
		sourceColumn: Paid ROI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total ROI'
		dataType: double
		lineageTag: e0bc681b-8ce1-4865-95b2-ba79dea34cc9
		summarizeBy: sum
		sourceColumn: Total ROI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Orders
		dataType: int64
		formatString: 0
		lineageTag: ef345d39-1798-4d6d-ae31-0fce4e59fbf8
		summarizeBy: sum
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

	column Impressions
		dataType: int64
		formatString: 0
		lineageTag: f29bb625-8310-4043-b0f6-95119ff11e1b
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

	column Clicks
		dataType: int64
		formatString: 0
		lineageTag: 4452088c-baa9-417d-be9d-4f516a735df7
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

	partition 'Target VS Achieved-Fk' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1kC_MKRIbnrqCfHjvYNUP6URIJDGr_yUmTvB8x0B2wHM/edit?gid=2082728106#gid=2082728106"),
				    #"Target VS Achieved_Table" = Source{[name="Flipkart - Targets vs Achievement",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Target VS Achieved_Table", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Account", type text}, {"Platform", type text}, {"Sale Type", type text}, {"Type", type text}, {"Ad Sales", type number}, {"Overall Sales", Int64.Type}, {"Paid ROI", type number}, {"Spends", Int64.Type}, {"Total ROI", type number}, {"Orders", Int64.Type}, {"Impressions", Int64.Type}, {"Clicks", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Account] = "Jockey"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

