table 'Target VS Achieved'
	lineageTag: b5b01ec0-d9e6-4687-b0c1-a5dedc3b6da2

	measure CVR_TA = DIVIDE((SUM('Target VS Achieved'[Orders])),(SUM('Target VS Achieved'[Clicks])),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8b731f67-6f30-4f45-95d8-329a6eacbe3d

	measure CTR_ta = DIVIDE((SUM('Target VS Achieved'[Clicks])),(SUM('Target VS Achieved'[Impressions])),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 09bc8070-d4e2-45e2-99c5-c2dcc5e5ca27

	measure AOV_ta = DIVIDE((SUM('Target VS Achieved'[Sales])),(SUM('Target VS Achieved'[Orders])),0)
		lineageTag: c3c2a37d-15c6-438a-9802-1643ebe2dbf7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ACOS_TA = DIVIDE((SUM('Target VS Achieved'[Spends])),(SUM('Target VS Achieved'[Sales])),0)
		lineageTag: 457957ad-8149-4a8f-9815-f058047060b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ROAS_TA = DIVIDE((SUM('Target VS Achieved'[Sales])),(SUM('Target VS Achieved'[Spends])),0)
		lineageTag: 192306b0-2f43-428c-a2ef-d1aa758472c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure actual_spends = ```
			CALCULATE(SUM('public amazon_paid'[Spend]),ALL('Target VS Achieved'),USERELATIONSHIP( 'public amazon_paid'[date],'Target VS Achieved'[Date])) 
			
			```
		lineageTag: 773d8067-8031-49ef-8689-07da848249c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% change_spends_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Spends] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Spend] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 89493c04-690c-401e-818b-fc2939673f75

	measure actual_orders = CALCULATE(SUM('public amazon_paid'[Orders]))
		formatString: 0
		lineageTag: 0b753955-2593-4cf0-97a0-e69c4a629778

	measure actual_sales = CALCULATE(SUM('public amazon_paid'[Sales]))
		lineageTag: e0934d9d-51a6-442f-b708-6ffe3b9a41c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure actual_clicks = CALCULATE(SUM('public amazon_paid'[Clicks]))
		formatString: 0
		lineageTag: a03f68ea-745a-4bd8-8430-e80374e7d787

	measure actual_impressions = CALCULATE(SUM('public amazon_paid'[Impressions]))
		formatString: 0
		lineageTag: ec43e604-1164-40cc-a5bc-377acf205fc7

	measure '% change_clicks_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Clicks] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Clicks] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 316fcd8c-24f5-455b-b255-da89a41754e8

	measure '% change_orders_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Orders] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Orders] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: df54f8fa-6aee-4921-992c-96bec6bf82d4

	measure '% change_sales_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Sales] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Sales] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 88136455-73f1-4636-9697-33f7afd23361

	measure '% change_impressions_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Impressions] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Impressions] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5261d76d-ba7e-43d1-bc40-c8e1f4179d21

	column Impressions
		dataType: double
		lineageTag: dfbfc95e-ecfd-4dd7-9ec3-48a64d7afc27
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Clicks
		dataType: double
		lineageTag: 6930034a-9a1b-4851-8743-c126f3b665ab
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Spends
		dataType: int64
		formatString: 0
		lineageTag: 5db52557-6278-44e0-8172-257c76c7a559
		summarizeBy: sum
		sourceColumn: Spends

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: double
		lineageTag: a7c3309c-76ad-40ff-94b9-5adf277391bb
		summarizeBy: sum
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 77127840-311e-4512-afb9-f98653c14ebc
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CTR
		dataType: double
		lineageTag: 438e24a9-e61d-40f2-9100-4484e3bce596
		summarizeBy: sum
		sourceColumn: CTR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CPC
		dataType: double
		lineageTag: 1e4dd370-a18b-474d-a384-af9ce35e2d9e
		summarizeBy: sum
		sourceColumn: CPC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CVR
		dataType: double
		lineageTag: 4769a31c-0276-4473-a280-612c04a8baf6
		summarizeBy: sum
		sourceColumn: CVR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AOV
		dataType: double
		lineageTag: 1bae12fd-d8ef-422b-9480-fe8bf2360fc3
		summarizeBy: sum
		sourceColumn: AOV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ROI
		dataType: double
		lineageTag: 01843d61-c013-4706-bfd3-c66437ad5ae8
		summarizeBy: sum
		sourceColumn: ROI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 85e4b27c-ba67-4764-bb21-66acc73288ec
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 3370f963-d35f-4782-acb6-021a5707aa5c
			defaultHierarchy: LocalDateTable_964fc65a-c811-4fbe-9e61-0a181a07267a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Target VS Achieved' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Z8q637lN1Fymvf04HEbakg_HdDybg_RrO4R846rZSzc/edit?gid=1273214790#gid=1273214790"),
				    #"Target VS Achieved_Table" = Source{[name="Target VS Achieved - Amazon",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Target VS Achieved_Table", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Impressions", type number}, {"Clicks", type number}, {"Spends", Int64.Type}, {"Orders", type number}, {"Sales", type number}, {"CTR", type number}, {"CPC", type number}, {"CVR", type number}, {"AOV", type number}, {"ROI", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

