table 'Target VS Achieved-Fk'
	lineageTag: afed3046-2f1e-4502-8bf6-8fb81068ecda

	column Impressions
		dataType: double
		lineageTag: 89c2b809-2a6a-4943-ac0c-969c43d10093
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Clicks
		dataType: double
		lineageTag: 5e15e05e-0b25-497c-8ee3-90ac4d8eb057
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Spends
		dataType: int64
		formatString: 0
		lineageTag: ab5045f4-753d-4790-9138-69b46b63bfcc
		summarizeBy: sum
		sourceColumn: Spends

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: int64
		formatString: 0
		lineageTag: 91e4a87b-dbd0-48fb-bb5a-02a28e4779f6
		summarizeBy: sum
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: cb50b1bc-66e3-4ffd-abdb-4e392415ea6f
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CTR
		dataType: double
		lineageTag: aaee7bde-ebdb-4bb7-9183-07ef258522cf
		summarizeBy: sum
		sourceColumn: CTR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CPC
		dataType: double
		lineageTag: 4938a8b7-0a2e-4697-aa68-348767ba7d27
		summarizeBy: sum
		sourceColumn: CPC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CVR
		dataType: double
		lineageTag: 36deffb7-9729-48f0-ad3e-a73bac59bc4f
		summarizeBy: sum
		sourceColumn: CVR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AOV
		dataType: double
		lineageTag: 447343e8-9031-4a19-b9c1-c7c451f71792
		summarizeBy: sum
		sourceColumn: AOV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ROI
		dataType: double
		lineageTag: 5234bbc3-473b-4324-86d2-5e7c0389c9de
		summarizeBy: sum
		sourceColumn: ROI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d10b9a61-e2de-4146-b73f-e389b3058d0e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 318ec229-eaf0-415e-9cb0-e02d18436e33
			defaultHierarchy: LocalDateTable_770c368e-deec-412f-9332-4fe1f12d9c96.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Target VS Achieved-Fk' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Z8q637lN1Fymvf04HEbakg_HdDybg_RrO4R846rZSzc/edit?gid=1273214790#gid=1273214790"),
				    #"Target VS Achieved_Table" = Source{[name="Target VS Achieved - Flipkart",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Target VS Achieved_Table", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Impressions", type number}, {"Clicks", type number}, {"Spends", Int64.Type}, {"Orders", Int64.Type}, {"Sales", type number}, {"CTR", type number}, {"CPC", type number}, {"CVR", type number}, {"AOV", type number}, {"ROI", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

