table 'Target VS Achieved'
	lineageTag: b5b01ec0-d9e6-4687-b0c1-a5dedc3b6da2

	measure CVR_TA = DIVIDE((SUM('Target VS Achieved'[Orders])),(SUM('Target VS Achieved'[Clicks])),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8b731f67-6f30-4f45-95d8-329a6eacbe3d

	measure CTR_ta = DIVIDE((SUM('Target VS Achieved'[Clicks])),(SUM('Target VS Achieved'[Impressions])),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 09bc8070-d4e2-45e2-99c5-c2dcc5e5ca27

	measure AOV_ta = DIVIDE((SUM('Target VS Achieved'[Sales])),(SUM('Target VS Achieved'[Orders])),0)
		lineageTag: c3c2a37d-15c6-438a-9802-1643ebe2dbf7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ACOS_TA = DIVIDE((SUM('Target VS Achieved'[Spends])),(SUM('Target VS Achieved'[Sales])),0)
		lineageTag: 457957ad-8149-4a8f-9815-f058047060b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ROAS_TA = DIVIDE((SUM('Target VS Achieved'[Sales])),(SUM('Target VS Achieved'[Spends])),0)
		lineageTag: 192306b0-2f43-428c-a2ef-d1aa758472c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% change_spends_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Spends] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Spend] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 89493c04-690c-401e-818b-fc2939673f75

	measure actual_clicks = CALCULATE(SUM('public amazon_paid'[Clicks]))
		formatString: 0
		lineageTag: a03f68ea-745a-4bd8-8430-e80374e7d787

	measure actual_impressions = CALCULATE(SUM('public amazon_paid'[Impressions]))
		formatString: 0
		lineageTag: ec43e604-1164-40cc-a5bc-377acf205fc7

	measure '% change_clicks_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Clicks] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Clicks] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 316fcd8c-24f5-455b-b255-da89a41754e8

	measure '% change_orders_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Orders] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Orders] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: df54f8fa-6aee-4921-992c-96bec6bf82d4

	measure '% change_sales_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Sales] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Sales] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 88136455-73f1-4636-9697-33f7afd23361

	measure '% change_impressions_tva' =
			
			VAR BaselineSpends = SUM ('Target VS Achieved'[Impressions] )
			VAR ComparisonSpends =
			    CALCULATE (
			        SUM ( 'public amazon_paid'[Impressions] )
			    )
			VAR Result =
			    DIVIDE (
			        ComparisonSpends,
			        BaselineSpends,
			        0
			    )
			RETURN
			    Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5261d76d-ba7e-43d1-bc40-c8e1f4179d21

	measure CVR% = DIVIDE('public amazon_paid'[CVR], 'Target VS Achieved'[CVR_TA])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e0be2ad0-def3-4033-8ff6-c1be76d5552a

	measure CPC_TA = DIVIDE((SUM('Target VS Achieved'[Spends])),(SUM('Target VS Achieved'[Clicks])),0)
		lineageTag: f2c7f6c9-45c6-49f2-8327-ec5d22fccc80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %-CPC = DIVIDE('public amazon_paid'[CPC_], 'Target VS Achieved'[CPC_TA],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7caf67ca-6894-45ef-b829-c1afb608b8f2

	measure '% AOV' = ```
			DIVIDE('public amazon_paid'[AOV], 'Target VS Achieved'[AOV_ta], 0) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f960ef8b-b5fd-4a10-b331-3bbd1c898264

	measure ROI_TA = DIVIDE((SUM('Target VS Achieved'[Sales])),(SUM('Target VS Achieved'[Spends])),0)
		lineageTag: ae5a0292-100f-4133-8c8f-ecd66f56ace5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% ROI' = DIVIDE('public amazon_paid'[actual_ROI], 'Target VS Achieved'[ROI_TA], 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ea049aa6-11fb-4065-9d6c-32007a4447aa

	measure '% CTR' = DIVIDE('public amazon_paid'[CTR_], 'Target VS Achieved'[CTR_ta], 0)
		lineageTag: 1d8f3894-2e0c-45c9-a46f-5de0049df884

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Spends
		dataType: int64
		formatString: 0
		lineageTag: 5db52557-6278-44e0-8172-257c76c7a559
		summarizeBy: sum
		sourceColumn: Spends

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: int64
		lineageTag: 77127840-311e-4512-afb9-f98653c14ebc
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Account
		dataType: string
		lineageTag: cf08fc5c-76fb-45fa-9aab-1233ab352745
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: 376c2a32-d20f-464d-abe0-08dbce3a1fc8
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column 'Sale Type'
		dataType: string
		lineageTag: e9a108b3-682a-41f4-88b5-401352ecb074
		summarizeBy: none
		sourceColumn: Sale Type

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: cca941a2-6240-4e3e-8008-d0237c65db2a
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Overall Sales'
		dataType: int64
		formatString: 0
		lineageTag: 13670bbc-9830-47ad-a5d8-45c992222f43
		summarizeBy: sum
		sourceColumn: Overall Sales

		annotation SummarizationSetBy = Automatic

	column 'Paid ROI'
		dataType: double
		lineageTag: fd32f587-742f-46cd-9608-f21e0ab58b74
		summarizeBy: sum
		sourceColumn: Paid ROI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total ROI'
		dataType: double
		lineageTag: 70f27891-fb9a-4788-b0a6-7ac788d98f75
		summarizeBy: sum
		sourceColumn: Total ROI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Orders
		dataType: int64
		formatString: 0
		lineageTag: 0ffceee1-e335-4f8a-a296-983f58d722f2
		summarizeBy: sum
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

	column Sales_1
		dataType: int64
		formatString: 0
		lineageTag: 51fb9aca-c884-4f59-9127-12ae8aec9d55
		summarizeBy: sum
		sourceColumn: Sales_1

		annotation SummarizationSetBy = Automatic

	column Impressions
		dataType: int64
		formatString: 0
		lineageTag: 7fb97096-b46e-4bd3-b4e0-a1ea11b4e302
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

	column Clicks
		dataType: int64
		formatString: 0
		lineageTag: 8eee9206-6fb4-47ad-bdec-8fcd0e59f306
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

	partition 'Target VS Achieved' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1kC_MKRIbnrqCfHjvYNUP6URIJDGr_yUmTvB8x0B2wHM/edit?gid=773646717#gid=773646717"),
				    #"Amazon - Targets vs Achievement_Table" = Source{[name="Amazon - Targets vs Achievement",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Amazon - Targets vs Achievement_Table", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Account", type text}, {"Platform", type text}, {"Sale Type", type text}, {"Type", type text}, {"Sales", Int64.Type}, {"Orders", Int64.Type}, {"Overall Sales", Int64.Type}, {"Paid ROI", type number}, {"Sales_1", Int64.Type}, {"Spends", Int64.Type}, {"Total ROI", type number}, {"Impressions", Int64.Type}, {"Clicks", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Account] = "Jockey"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

