table 'test model'
	lineageTag: 58c5419d-7e32-49f0-91be-7eb97289fc0a

	column GIF
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4dde1987-1d40-420d-a006-d15fdb4a93b9
		summarizeBy: none
		sourceColumn: GIF

		variation Variation
			isDefault
			relationship: 2457a7e2-5b92-405b-be3d-a8a44c1be4cd
			defaultHierarchy: LocalDateTable_32d112e5-830e-41e4-8771-7d5aaf88ef5c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Impressions
		dataType: int64
		formatString: 0
		lineageTag: e4cd6e47-eef3-4184-a0b1-1c3fcac4ed93
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

	column Clicks
		dataType: int64
		formatString: 0
		lineageTag: 7cf7e61a-20c9-4e89-8a04-4c47ce13bbfb
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

	column Spends
		dataType: int64
		formatString: 0
		lineageTag: bf01d0ea-ee5f-4ff1-bcb5-02ab12611ee5
		summarizeBy: sum
		sourceColumn: Spends

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: int64
		formatString: 0
		lineageTag: 8c741097-f6e1-434c-8b1f-81530c6aa8d2
		summarizeBy: sum
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: int64
		formatString: 0
		lineageTag: cf298a09-4646-474a-aab7-4bf320212a58
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column CTR
		dataType: double
		lineageTag: 56d90def-7118-4c0e-8a5e-add9470d6d43
		summarizeBy: sum
		sourceColumn: CTR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CPC
		dataType: double
		lineageTag: 00634f43-0ae8-484b-916c-9f6a0858e249
		summarizeBy: sum
		sourceColumn: CPC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CVR
		dataType: double
		lineageTag: 63dc32fd-6225-4c9e-85f0-e5059cab8758
		summarizeBy: sum
		sourceColumn: CVR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AOV
		dataType: double
		lineageTag: f60e2c95-fc62-4698-8aa4-8f437b6db96c
		summarizeBy: sum
		sourceColumn: AOV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ROI
		dataType: double
		lineageTag: 992cc73d-8a9f-4b36-8901-6185cdac2df8
		summarizeBy: sum
		sourceColumn: ROI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'test model' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Z8q637lN1Fymvf04HEbakg_HdDybg_RrO4R846rZSzc/edit?gid=1273214790#gid=1273214790"),
				    Sale_2024_Table = Source{[name="Sale_2024",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sale_2024_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"GIF", type date}, {"Impressions", Int64.Type}, {"Clicks", Int64.Type}, {"Spends", Int64.Type}, {"Orders", Int64.Type}, {"Sales", Int64.Type}, {"CTR", type number}, {"CPC", type number}, {"CVR", type number}, {"AOV", type number}, {"ROI", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

